In [1]:
import os
import sys
import torch
import accimage
import numpy as np
import pandas as pd
from PIL import Image
from imageio import imread
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, models, transforms, set_image_backend, get_image_backend
import torch.nn.functional as F
import pickle
import train_utils
import data_utils
import os
import gc
import sys
import torch
import psutil
import pickle
import numpy as np
import pandas as pd
import torch.nn as nn
from sklearn import metrics
from collections import Counter
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torchvision import models, set_image_backend
set_image_backend('accimage')
import data_utils
import train_utils
root_dir_coad = '/n/mounted-data-drive/COAD/'


In [2]:
sa_train, sa_val = data_utils.load_COAD_train_val_sa_pickle()
root_dir = '/n/mounted-data-drive/COAD/'
magnification = '10.0'
batch_type = 'slide'

train_transform = train_utils.transform_train


In [3]:
class TCGADataset_tiled_slides(Dataset):
    """
    TCGA slide dataset. Each slide is linked to its tiles via a label.
    """
    def __init__(self, sample_annotations, root_dir, transform=None, loader=data_utils.default_loader, magnification='5.0'):
        """
        Args:
            sample_annot (dict): dictionary of sample names and their respective labels.
            root_dir (string): directory containing all of the samples and their respective images.
            transform (callable, optional): optional transform to be applied on the images of a sample.
            loader specifies image backend: use accimage
            magnification: tile magnification
        """
        self.sample_names = list(sample_annotations.keys())
        self.sample_labels = list(sample_annotations.values())
        
        self.root_dir = root_dir
        self.transform = transform
        self.loader = loader
        self.magnification = magnification
        self.batch_type = batch_type
        self.img_dirs = [self.root_dir + sample_name + '.svs/' \
                         + sample_name + '_files/' + self.magnification for sample_name in self.sample_names]
        self.jpegs = [os.listdir(img_dir) for img_dir in self.img_dirs]
        self.all_jpegs = []
        self.all_labels = []
        self.jpg_to_sample = []
        self.coords = []
        
        for idx,(im_dir,label,l) in enumerate(zip(self.img_dirs,self.sample_labels,self.jpegs)):
            sample_coords = []
            for jpeg in l:
                # build tile dataset
                self.all_jpegs.append(im_dir+'/'+jpeg)
                # label for each tile
                self.all_labels.append(label)
                # tracks slide membership at a tile level
                self.jpg_to_sample.append(idx)
                # store tile coordinates
                x,y = jpeg[:-5].split('_') # 'X_Y.jpeg'
                x,y = int(x), int(y)
                self.coords.append(torch.tensor([x,y]))
            
    def __len__(self):
        return len(self.all_jpegs)
        
    def __getitem__(self, idx):
        image = self.loader(self.all_jpegs[idx])
        if self.transform is not None:
            image = self.transform(image)
        if image.shape[1] < 256 or image.shape[2] < 256:
            image = data_utils.pad_tensor_up_to(image,256,256,channels_last=False)
        return image, self.all_labels[idx], self.coords[idx],self.jpg_to_sample[idx]

In [4]:
train_set = TCGADataset_tiled_slides(sa_train, root_dir, transform=train_transform, magnification='5.0')
train_loader = DataLoader(train_set, batch_size=512, pin_memory=True, num_workers=20)

In [5]:
state_dict_file = '/n/tcga_models/resnet18_WGD_10x.pt'
device = torch.device('cuda', 0)
output_shape = 1

In [6]:
resnet = models.resnet18(pretrained=False)
resnet.fc = nn.Linear(2048, output_shape, bias=True)
saved_state = torch.load(state_dict_file, map_location=lambda storage, loc: storage)
resnet.load_state_dict(saved_state)
resnet.fc = nn.Linear(2048, 2048, bias=False)
resnet.fc.weight.data = torch.eye(2048)
resnet.cuda(device=device)
for param in resnet.parameters():
    param.requires_grad = False

In [7]:
def pool_fn(x):
    #v,a = torch.max(x,0)
    v = torch.mean(x,0)
    return v

class pool_and_classify(nn.Module):
    def __init__(self, pool_fn, n_inputs, n_outputs):
        super(pool_and_classify, self).__init__()
        self.fc = nn.Linear(n_inputs,n_outputs)
        self.pool = pool_fn
    def forward(self,h,embeddings,slides):
        embeddings = [torch.masked_select(embeddings,(slide_membership == slide).view(-1,1)).view(-1,2048) for slide in slides]
        pooled = [self.pool(h) for h in embeddings]
        logits = self.fc(torch.stack(pooled))
        return logits
    
slide_level_classification_layer = pool_and_classify(pool_fn,2048,1)
slide_level_classification_layer.cuda()

pool_and_classify(
  (fc): Linear(in_features=2048, out_features=1, bias=True)
)

In [8]:
e = 0
learning_rate = 1e-4
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(slide_level_classification_layer.parameters(), lr = learning_rate)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=10, min_lr=1e-8)

In [9]:
# track number of slides seen
p_update = torch.tensor(0.,device=device)
# store embeddings, labels, and memberships
embeddings = []
slide_membership = []
step = 0
batches = 0
slide_labels = torch.tensor(train_set.sample_labels, device=device)
for batch,labels,coords,idxs in train_loader:
    # get embeddings
    batch,labels,coords,idxs = batch.cuda(),labels.cuda(),coords.cuda(),idxs.cuda()
    if len(embeddings) == 0:
        current_slide = torch.min(idxs)
    # append each batched results
    embeddings.extend(resnet(batch))
    slide_membership.extend(idxs)
    
    p_update += 0.0001
    batches+=1
    
    if torch.rand(1,device=device) < p_update:
        slide_membership = torch.stack(slide_membership)
        slides = torch.unique(torch.tensor(slide_membership),sorted=True)
        loss = torch.tensor(0.,device=device)
        embeddings = torch.stack(embeddings)
        slide_labels = torch.stack(slide_labels)
        torch.index_select(slide_labels,0,torch.tensor(slides,device=device))
        for slide in slides:
            logits = slide_level_classification_layer(embeddings[slide_membership == slide,:])
            loss += criterion(logits,slide_labels[slide_membership == slide][0].float().view(-1))
        break    
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()    
        embeddings = []
        slide_labels = []
        print(step,batches,torch.max(slide_membership).detach().cpu().numpy())
        slide_membership = []
        step+=1
        batches = 0
        p_update = torch.tensor(0.,device=device)
        
slide_membership = torch.stack(slide_membership)
slides = list(set(torch.squeeze(slide_membership).detach().cpu().numpy()))
loss = torch.tensor(0.,device=device)
embeddings = torch.stack(embeddings)
slide_labels = torch.stack(slide_labels)
for slide in slides:
    pooled = pool_fn(embeddings[slide_membership == slide,:])
    logits = slide_level_classification_layer(pooled)
    loss += criterion(logits,slide_labels[slide_membership == slide][0].float().view(-1))

loss.backward()
optimizer.step()
optimizer.zero_grad()        

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [39]:
list_em = [torch.masked_select(embeddings,slide_membership == slide).view(-1,2048) for slide in slides]

In [39]:
slide_labels = torch.tensor(train_set.sample_labels, device=device)


tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 0], device='cuda:0')

tensor([0, 1, 2, 3])

torch.Size([324])

In [11]:
slide_membership.shape

torch.Size([73728])

tensor([[0.1145, 0.1475, 0.1570,  ..., 0.7910, 1.0237, 0.9910],
        [0.6682, 0.7999, 0.7649,  ..., 0.3765, 0.2672, 0.3765],
        [1.1181, 1.2128, 0.7971,  ..., 1.4313, 0.9947, 1.1140],
        ...,
        [1.0344, 0.8466, 0.8967,  ..., 0.4271, 0.6927, 0.4957],
        [0.8224, 0.7230, 1.0966,  ..., 0.9042, 1.0291, 0.9912],
        [1.1212, 1.5049, 1.3071,  ..., 0.4562, 0.4927, 0.5448]],
       device='cuda:0')